<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/GitVisualizer.App/GitVisualizer.App.csproj" />
    <ProjectReference Include="../../src/GitVisualizer.Infrastructure/GitVisualizer.Infrastructure.csproj" />
    <PackageReference Include="CommunityToolkit.Mvvm" ExcludeAssets="analyzers" />
  </ItemGroup>
</Project>

